version: '2'
services:
  web:
    build: web/
    links:
     - db
    ports:
     - "80:80"
     - "9000:9000"
    volumes:
     - ../../:/var/www/html
  db:
    build: mysql/
    ports:
     - "3306:3306"